### ISSUE TITLE
Potential issue in cpp_src/tools/fsops.cc: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [sagpant/reindexer#1]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

1 instance of this defect were found in the following locations:
---
**Instance 1**
File : `cpp_src/tools/fsops.cc` 
Function: `_stat64i32` 
https://github.com/sagpant/reindexer/blob/54bf5ad40f3590e9b4dd6287f21e3b4774c8ae2c/cpp_src/tools/fsops.cc#L188
Code extract:

```cpp
#ifdef _WIN32
		if (_access(directory.c_str(), 0) == 0) {
			struct _stat status;
			_stat(directory.c_str(), &status); <------ HERE
			if (status.st_mode & _S_IFDIR) return true;
		}
```

**How can I fix it?** 
Correct reference usage found in `cpp_src/tools/fsops.cc` at line `140`.
https://github.com/sagpant/reindexer/blob/54bf5ad40f3590e9b4dd6287f21e3b4774c8ae2c/cpp_src/tools/fsops.cc#L140
Code extract:

```cpp
FileStatus Stat(const string &path) {
#ifdef _WIN32
	struct _stat state;
	if (_stat(path.c_str(), &state) < 0) return StatError; <------ HERE
	return (state.st_mode & _S_IFDIR) ? StatDir : StatFile;
#else
```

**Comment by siva-msft** [comment]
lgtm.
